### ISSUE TITLE
Can i "create" an item?

### ISSUE THREAD

**Issue by jarocajavi** [gamerpotion/DarkBindings#1]
Hello, thanks for your work with DarkBindings, because is easier than other mods like "nbt crafting" or "kubejs".

II want to ask if is there any way to create a custom item like compressed tnt with 9x tnt recipe and the result will be enchanted for example, or with another name for uses futures.

I try create a hard recipe for nuke in my server and can be control its crafting with a "barrier" or "bedrock.

Thanks for your help!

**Comment by gamerpotion** [comment]
> Hello, thanks for your work with DarkBindings, because is easier than other mods like "nbt crafting" or "kubejs".
> 
> II want to ask if is there any way to create a custom item like compressed tnt with 9x tnt recipe and the result will be enchanted for example, or with another name for uses futures.
> 
> I try create a hard recipe for nuke in my server and can be control its crafting with a "barrier" or "bedrock.
> 
> Thanks for your help!

Hi, thanks for your query and using the mod! :)

Unfortunately its not possible to do custom with the mod, however, if you tell me what you want added - I could look into adding it into the mod and updating with it?

if you tell me the IDs (F3+H) for the items and recipe I can take a look

**Comment by jarocajavi** [comment]
Hello, thanks for the fast answer.

The recipe i looking for is convert 9xtnt (vanilla) to "TNT_Compressed" (same item but with different nbt tags to use it for another recipe.

So, the tree will be this:
9x minecraft:tnt = 1 minecraft:compressed_tnt (for example, the name is not important but the item itself will be the same item but with nbt tags some how and ¿?enchanted¿?

The second step i want to compress more:
9x compressed_tnt = hyper_compressed_tnt...

and there we go

**Comment by gamerpotion** [comment]
> Hello, thanks for the fast answer.
> 
> The recipe i looking for is convert 9xtnt (vanilla) to "TNT_Compressed" (same item but with different nbt tags to use it for another recipe.
> 
> So, the tree will be this: 9x minecraft:tnt = 1 minecraft:compressed_tnt (for example, the name is not important but the item itself will be the same item but with nbt tags some how and ¿?enchanted¿?
> 
> The second step i want to compress more: 9x compressed_tnt = hyper_compressed_tnt...
> 
> and there we go

I think in this instance for your requirement, nbt crafting would be an easier option. It would involve a lot more to do it the vanilla way, sorry.

**Comment by jarocajavi** [comment]
> > Hello, thanks for the fast answer.
> > The recipe i looking for is convert 9xtnt (vanilla) to "TNT_Compressed" (same item but with different nbt tags to use it for another recipe.
> > So, the tree will be this: 9x minecraft:tnt = 1 minecraft:compressed_tnt (for example, the name is not important but the item itself will be the same item but with nbt tags some how and ¿?enchanted¿?
> > The second step i want to compress more: 9x compressed_tnt = hyper_compressed_tnt...
> > and there we go
> 
> I think in this instance for your requirement, nbt crafting would be an easier option. It would involve a lot more to do it the vanilla way, sorry.

No prob, finally with your mod i make custom recipes with items from several mods, so the special tnt and the rest of i need its done thanks (again) to your mod. :) More easy than nbt crafting.
